### ISSUE TITLE
Javadoc generation fails if module name contains non-terminal restricted keyword

### ISSUE THREAD

**Issue by cowwoc** [codehaus-plexus/plexus-languages#23]
See https://stackoverflow.com/a/36322692/14731 for some background context

Per the JLS, these restricted keywords are allowed as long as they do not appear in a terminal position. So a module name of "one.to.three" is legal but "one.three.to" is illegal.
* Open testcase
* Run `mvn compile -e`
* Notice that `javac` accepts {{module-info.java}} but the Maven plugin incorrectly claims it contains a syntax error.

Specifically, I get:

```
com.thoughtworks.qdox.parser.ParseException: syntax error @[1,12] in file:/C:/Users/Gili/Documents/3rdparty/javadoc-module-name-contains-to/src/main/java/module-info.java
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1781)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1903)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1762)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
	at com.thoughtworks.qdox.library.SourceFolderLibrary.resolveJavaModule(SourceFolderLibrary.java:91)
	at com.thoughtworks.qdox.library.SourceFolderLibrary.addSourceFolder(SourceFolderLibrary.java:60)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSourceFolder(SortedClassLibraryBuilder.java:179)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceFolder(JavaProjectBuilder.java:188)
	at org.codehaus.plexus.languages.java.jpms.SourceModuleInfoParser.fromSourcePath(SourceModuleInfoParser.java:53)
	at org.codehaus.plexus.languages.java.jpms.LocationManager.getMainModuleDescriptor(LocationManager.java:263)
	at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths(LocationManager.java:114)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.getPackageNamesRespectingJavaModules(AbstractJavadocMojo.java:4427)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2022)
	at org.apache.maven.plugins.javadoc.JavadocJar.doExecute(JavadocJar.java:189)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute(AbstractJavadocMojo.java:1931)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more
```

**Comment by cowwoc** [comment]
[testcase.zip](https://github.com/codehaus-plexus/plexus-languages/files/2727707/testcase.zip)

**Comment by cowwoc** [comment]
This issue is currently blocking https://jira.qos.ch/browse/SLF4J-428

**Comment by rfscholte** [comment]
This is already fixed in QDox ( have a closer look at the stacktrace ) and plexus-java is already using its latest version.
The problem here is that maven-javadoc-plugin also has a direct dependency on QDox, used for the several `javadoc:fix` goals. However, in the plugin the version hasn't been updated yet.
The solution is quite simple, ensure  that the maven-javadoc-plugin is using the latest version of QDox too.
